### ISSUE TITLE
Segmentation fault when using --dims

### ISSUE THREAD

**Issue by flemmens** [hobuinc/untwine#150] opened 2024-01-08 14:12 UTC
Hello,

When I am trying to use the --dims option, I receive a "Segmentation fault" error.

This works fine:
```
untwine --files=mydata.las --single_file=true --output_dir=out
```

This does not work (Segmentation fault):
```
untwine --files=mydata.las --single_file=true --dims="X, Y, Z" --output_dir=out
```

Is this the correct way to use the --dims option ? There is not much info in the README. I would like to keep only X,Y,Z values.

**Comment by abellgithub** [comment] 2024-01-08 15:14
"output_dir" is for multi-file output. Just specify the output file as an argument.

I'll try to harden the argument handling.

**Comment by abellgithub** [comment] 2024-01-09 14:41
I forgot that this was correct syntax for the filename. I can't reproduce, so if you have a file that causes this behavior and can post, I can take a look.

**Comment by abellgithub** [comment] 2024-01-11 19:14
Reproduced.

**Comment by abellgithub** [comment] 2024-01-28 21:29
Fixed by #151

**Closed by abellgithub** 2024-01-28 21:29 UTC
